### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'permission.policies.map')

### ISSUE THREAD

**Issue by tuler** [zerodevapp/capabilities-examples#1]
After the upgrade to viem 2.16.3 and the new policies API the session-keys example does not work anymore.

**Comment by tuler** [comment]
Even if we change the call to add a `policies: []` field to the `grantPermissions` call at [line 61](https://github.com/zerodevapp/capabilities-examples/blob/749b28db7b66add71cdaedb2827cf4243e727bb1/session-keys/src/app/Sessions.tsx#L61), 
viem [expects a policies field](https://github.com/wevm/viem/blob/f7afaa2e0c687e45fe85c8de51cbd8a12f2318a4/src/experimental/erc7715/actions/grantPermissions.ts#L170) in the wallet [grantedPermissions response](https://github.com/zerodevapp/sdk/blob/9c278f2b3a203c1713f892e2d6480dd70a051d7f/wallet/KernelEIP1193Provider.ts#L484). But there is none.

**Comment by tuler** [comment]
Any news on this issue?

**Comment by jstinhw** [comment]
It should be fixed with the [latest fix](https://github.com/zerodevapp/capabilities-examples/commit/e41b2d9967a77432d5b2dbceb0596a4fe7c41f06). 

Please reopen the issue if it's not the case
